---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    ms: '{{ ms }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u darshangtevarimatha@gmail.com -p Ilovemanu007 darshangt.jfrog.io 
    
    - name: pull an image
      shell: docker pull darshangt.jfrog.io/jenkins-cicd-docker-cicd/app-a/{{ ms }}:{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 9000:8080 darshangt.jfrog.io/jenkins-cicd-docker-cicd/app-a/{{ ms }}:{{ build_number }}
 
   
