---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u yourdevopsbro@gmail.com -p Darshangt@7 devopsbro.jfrog.io
    
    - name: pull an image
      shell: docker pull devopsbro.jfrog.io/docker-docker-local/app-a/{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 9090:8080 darshangt.jfrog.io/docker-docker-local/app-a/{{ build_number }}
 
   
